import icons from "@/utils/icons";

export default [
	{
		path: '/admin',
		name: 'Home',
		icon: icons.home,
		permission: [''],
		group: 'home',
		skip: true,
	},
	{
		path: '/admin/orders',
		name: 'Orders',
		icon: icons.notification,
		permission: [''],
		group: 'orders',
		skip: false,
	},
	{
		path: '/admin/products',
		name: 'Products',
		icon: icons.list,
		permission: [''],
		group: 'orders',
		skip: false,
	},
	{
		path: '/admin/messages',
		name: 'Messages',
		icon: icons.message,
		permission: [''],
		group: 'contact',
		skip: false,
	},
	{
		path: '/admin/commercial',
		name: 'Commercial',
		icon: icons.image,
		permission: [''],
		group: 'CMS',
		skip: false,
	},
	{
		path: '/admin/about',
		name: 'About',
		icon: icons.book,
		permission: [''],
		group: 'CMS',
		skip: false,
	},
	{
		path: '/admin/contact_informatio',
		name: 'Contact Informatio',
		icon: icons.contact,
		permission: [''],
		group: 'CMS',
		skip: false,
	},
	{
		path: '/admin/recipes',
		name: 'Recipes',
		icon: icons.brush,
		permission: [''],
		group: 'CMS',
		skip: false,
	},
	{
		path: '/admin/users',
		name: 'Users',
		icon: icons.users,
		permission: [''],
		group: 'settings',
		skip: false,
	},
]